start_values = [
    30.0, # damagePhysical
    100.0, # health
    100.0, # resistancePhysical
    100.0, # damageMagical
    100.0, # mana
    100.0, # resistanceMagical
    5.0, # speed
    0.3, # attackSpeed
    100.0, # spellSpeed
    100.0, # regenerationMana
    100.0, # regenerationStamina
    100.0, # resistanceStatus
    10.0, # spread
    60.0, # range
    100.0, # dodgeRange
    100.0, # visualRange
    100.0, # critChance
    100.0, # critMultiplier
]

multipliers = [
    +3.0, #damagePhysical
    +10.0, # health
    +10.0, # resistancePhysical
    +10.0, # damageMagical
    +10.0, # mana
    +10.0, # resistanceMagical
    +0.50, # speed
    +0.03, # attackSpeed
    +10.0, # spellSpeed
    +10.0, # regenerationMana
    +10.0, # regenerationStamina
    +10.0, # resistanceStatus
    +1.0, #spread
    +6.0, #range
    +10.0, # dodgeRange
    +10.0, # visualRange
    +10.0, # critChance
    +10.0, # critMultiplier
]

