b2box_raylib_radians_diff = 3.0
cameraDecay = 10.0
dash_duration = 0.10000000149011612
dash_speed = 10000.0
draw_enemies_outside_screen = true
draw_level_collisions = false
enemyHearRange = 70.0
enemyHearRangeChasing = 100.0
enemyPatrolDistance = 90.0
enemySightRange = 130.01234436035156
enemySightRangeChasing = 250.0
enemy_walking_animation_fps = 10
fps = 60
free_camera = false
inEditor = true
in_editor = false
show_astar_path = true
show_attacks = true
show_attr_window = false
show_bounding_box = true
show_enemy_fov = true
show_enemy_texture = false
show_enemy_window = false
show_inv_window = false
show_spline_ui = false
strategy = 0