show_astar_path = true
show_enemy_fov = true
show_bounding_box = true
show_enemy_texture = false
show_attacks = true
show_attr_window = false
show_inv_window = false
show_enemy_window = false
free_camera = false
draw_level_collisions = false
draw_enemies_outside_screen = true
enemySightRange = +130.01234
enemySightRangeChasing = 250.0
enemyHearRange = 70.0
enemyHearRangeChasing = 100.0
enemyPatrolDistance = 90.0
fps = 60
enemy_walking_animation_fps = 8
strategy = 0

attrMultipliers = [
    3.0,
    10.0,
    10.0,
    10.0,
    10.0,
    10.0,
    0.50,
    0.03,
    10.0,
    10.0,
    10.0,
    10.0,
    1.0,
    6.0,
    10.0,
    10.0,
    10.0,
    10.0,
]
